site_name: Social Media Downloader Docs
site_url: https://nayandas69.github.io/smd-docsite
repo_url: https://github.com/nayandas69/Social-Media-Downloader
edit_uri: ""

theme:
  name: material
  language: en
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    admonition:
      note: material/information-outline
      tip: material/lightbulb-on-outline
      warning: material/alert-outline
      important: material/alert-circle-outline
      info: material/information

nav:
  - Home: index.md
  - Installation:
      - Requirements & Setup: installation.md
      - Troubleshooting Setup: troubleshooting.md
  - Usage:
      - How to Use: usage.md
      - Configuration Details: config-info.md
      - Supported Platforms: supported-platforms.md
      - FAQ: faq.md
  - Build:
      - Build Instructions: build.md
      - Changelog: changelog.md
      - Archive: archive.md
  - Development:
      - Roadmap: roadmap.md
  - Contribute: contribute.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.snippets

plugins:
  - search
  - glightbox
